app:
    resource: '@AppBundle/Controller/'
    type: annotation


app_listing:
    resource: "@AppBundle/Controller/ListingController.php"
    type: annotation

app_review:
    resource: "@AppBundle/Controller/ReviewController.php"
    type: annotation
